'use strict';

export const OPEN_LAUNCH_SCREEN = 'OPEN_LAUNCH_SCREEN';

export const OPEN_TASKS_LIST_SCREEN = 'OPEN_TASKS_LIST_SCREEN';

export const OPEN_CREATE_TASK_SCREEN = 'OPEN_CREATE_TASK_SCREEN';


export const START_DOWNLOADING = 'START_DOWNLOADING';

export const STOP_DOWNLOADING = 'STOP_DOWNLOADING';

export const OPEN_NAV_BAR = 'OPEN_NAV_BAR';

export const CLOSE_NAV_BAR = 'CLOSE_NAV_BAR';

