'use strict';

export const SPLASH_SCREEN = 'SPLASH_SCREEN';

export const LOGIN_SCREEN = 'LOGIN_SCREEN';

export const LAUNCH_SCREEN = 'LAUNCH_SCREEN';

export const TASKS_LIST_SCREEN = 'TASKS_LIST_SCREEN';

export const CREATE_TASK_SCREEN = 'CREATE_TASK_SCREEN';

export const TASK_DETAILS_SCREEN = 'TASK_DETAILS_SCREEN';

